basePath: /api
definitions:
  forms.ContactForm:
    properties:
      description:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      phone:
        type: string
      tour_id:
        type: integer
    required:
    - description
    - email
    - name
    - phone
    type: object
  forms.HelpWithTourForm:
    properties:
      id:
        type: integer
      name:
        type: string
      phone:
        type: string
      place:
        type: string
      when_date:
        type: string
    required:
    - name
    - phone
    - place
    - when_date
    type: object
  http.errorResponse:
    properties:
      message:
        type: string
    type: object
  http.getAllToursResponse:
    properties:
      currentPage:
        type: integer
      itemsPerPage:
        type: integer
      totalItems:
        type: integer
      totalPages:
        type: integer
      tourPlaces:
        items:
          type: string
        type: array
      tours:
        items:
          $ref: '#/definitions/tour.Tour'
        type: array
    type: object
  tour.DescriptionRoute:
    properties:
      default:
        items:
          type: string
        type: array
      next:
        items:
          type: string
        type: array
    type: object
  tour.Tour:
    properties:
      activity:
        items:
          type: string
        type: array
      book_tour_photos:
        type: string
      currency:
        type: string
      description_excursion:
        type: string
      description_route:
        $ref: '#/definitions/tour.DescriptionRoute'
      duration:
        type: integer
      gallery_photos:
        items:
          type: string
        type: array
      id:
        type: integer
      physical_rating:
        maximum: 5
        minimum: 1
        type: integer
      popular:
        type: boolean
      preview_photo:
        type: string
      price:
        type: integer
      quantity:
        type: integer
      route_photos:
        items:
          type: string
        type: array
      season:
        type: string
      slug:
        type: string
      tariff:
        type: string
      title:
        type: string
      tour_date:
        type: string
      tour_place:
        type: string
      tour_type:
        $ref: '#/definitions/tour.TourType'
    required:
    - activity
    - currency
    - description_excursion
    - description_route
    - duration
    - physical_rating
    - price
    - quantity
    - season
    - title
    - tour_date
    - tour_place
    - tour_type
    type: object
  tour.TourEditor:
    properties:
      activity:
        items:
          type: string
        type: array
      email:
        type: string
      id:
        type: integer
      location:
        items:
          type: string
        type: array
      name:
        type: string
      phone:
        type: string
      tour_date:
        type: string
    required:
    - activity
    - email
    - location
    - name
    - phone
    - tour_date
    type: object
  tour.TourType:
    enum:
    - Однодневный тур
    - Многодневный тур
    - Сити-тур
    - Эксклюзивный тур
    - Инфо-тур
    - Авторский тур
    type: string
    x-enum-varnames:
    - OneDayTour
    - MultiDayTour
    - CityTour
    - ExclusiveTour
    - InfoTour
    - AuthorsTour
host: 178.128.123.250:80
info:
  contact: {}
  title: SilkRoad App API
  version: "1.0"
paths:
  /countries:
    get:
      consumes:
      - application/json
      description: This method returns a list of all available countries
      produces:
      - application/json
      responses:
        "200":
          description: List of countries
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.errorResponse'
      summary: Returns a list of countries
      tags:
      - countries
  /form/contact_form:
    post:
      consumes:
      - application/json
      description: This method creates a new contact form and, if TourID is provided,
        sends tour details
      parameters:
      - description: Contact form data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/forms.ContactForm'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.errorResponse'
      summary: Create a contact form
      tags:
      - forms
  /form/help_with_tour_form:
    post:
      consumes:
      - application/json
      description: This method creates a new helpWithTour form
      parameters:
      - description: helpWithTour form data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/forms.HelpWithTourForm'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.errorResponse'
      summary: Create a help with tour form
      tags:
      - forms
  /tour_editor:
    post:
      consumes:
      - application/json
      description: This method allows users to create a custom tour by submitting
        their details and tour preferences. The tour data will also be sent to Telegram.
      parameters:
      - description: Custom tour data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/tour.TourEditor'
      produces:
      - application/json
      responses:
        "200":
          description: ID and creation status of the tour
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/http.errorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/http.errorResponse'
      summary: Create a custom tour
      tags:
      - tour
  /tours:
    get:
      consumes:
      - application/json
      description: Получение списка туров с возможностью фильтрации по местоположению,
        дате, названию, количеству, цене, продолжительности, популярности и другим
        параметрам
      parameters:
      - description: Tour place
        in: query
        name: tour_place
        type: string
      - collectionFormat: csv
        description: Quantity (array of integers)
        in: query
        items:
          type: integer
        name: quantity
        type: array
      - description: Minimum price
        in: query
        name: priceMin
        type: integer
      - description: Maximum price
        in: query
        name: priceMax
        type: integer
      - description: Duration
        in: query
        name: duration
        type: integer
      - description: Tour date
        in: query
        name: tour_date
        type: string
      - description: Search by title
        in: query
        name: search
        type: string
      - default: 4
        description: Limit for pagination
        in: query
        name: limit
        type: integer
      - default: 0
        description: Offset for pagination
        in: query
        name: offset
        type: integer
      - description: Filter by popular tours
        in: query
        name: popular
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.getAllToursResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.errorResponse'
      summary: Get all tours
      tags:
      - tours
    post:
      consumes:
      - application/json
      description: This method creates a new tour with the given input data
      parameters:
      - description: Tour input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/tour.Tour'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.errorResponse'
        "422":
          description: Invalid Tour Type
          schema:
            $ref: '#/definitions/http.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.errorResponse'
      summary: Creates a new tour
      tags:
      - tours
  /tours/{id}:
    get:
      consumes:
      - application/json
      description: This method returns the details of a specific tour by its ID
      parameters:
      - description: Tour ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Tour details
          schema:
            $ref: '#/definitions/tour.Tour'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.errorResponse'
      summary: Returns tour by ID
      tags:
      - tours
  /tours/photos/{tourID}:
    post:
      consumes:
      - multipart/form-data
      description: Uploads multiple photos for a specific tour by tourID, allowing
        the update of either the gallery or the route description.
      parameters:
      - description: Tour ID
        in: path
        name: tourID
        required: true
        type: integer
      - description: Type to update (gallery, route, preview, book)
        in: query
        name: photoType
        required: true
        type: string
      - description: Photos to upload
        in: formData
        name: photos
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: 'status: OK, message: Photos uploaded successfully'
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 'status: Bad Request, message: Invalid tourID, updateField
            or form data'
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 'status: Internal Server Error, message: Error message'
          schema:
            additionalProperties: true
            type: object
      summary: Upload photos for a tour
      tags:
      - tours
  /tours/prices:
    get:
      consumes:
      - application/json
      description: This method returns the minimum and maximum prices of all available
        tours
      produces:
      - application/json
      responses:
        "200":
          description: Min and Max tour prices
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.errorResponse'
      summary: Returns the minimum and maximum prices of all tours
      tags:
      - tours
  /tours/title/{slug}:
    get:
      consumes:
      - application/json
      description: This method returns the details of a specific tour based on its
        slug
      parameters:
      - description: Tour Slug
        in: path
        name: slug
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Tour details
          schema:
            $ref: '#/definitions/tour.Tour'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.errorResponse'
      summary: Returns tour details by slug
      tags:
      - tours
swagger: "2.0"
