name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY_NAME: "silkroad-api"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to DigitalOcean Docker Registry
        run: |
          echo "${{ secrets.ACCESS_TOKEN }}" | docker login registry.digitalocean.com -u docean --password-stdin

      - name: Проверка доступа к реестру
        run: curl -v https://registry.digitalocean.com/v2/

      - name: Build Docker image
        run: docker build -t registry.digitalocean.com/silkroad-api/silkroad-app:latest .

      - name: Push Docker image to DigitalOcean Registry
        run: docker push registry.digitalocean.com/silkroad-api/silkroad-app:latest

    outputs:
      image_name: registry.digitalocean.com/silkroad-api/silkroad-app
      image_tag: latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSHKEY }}

      - name: Log in to DigitalOcean Docker Registry
        run: | 
          echo "${{ secrets.ACCESS_TOKEN }}" | docker login registry.digitalocean.com -u "docean" --password-stdin

      - name: Deploy to DigitalOcean
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_IP }} << 'EOF'
            docker stop silkroad-app || true
            docker rm silkroad-app || true
            docker pull registry.digitalocean.com/silkroad-api/silkroad-app:latest
            docker run -d --name silkroad-app -p 80:80 \
              -e DB_HOST=${{ secrets.DB_HOST }} \
              -e DB_PORT=${{ secrets.DB_PORT }} \
              -e DB_NAME=${{ secrets.DB_NAME }} \
              -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -e DB_SSLMODE=${{ secrets.DB_SSLMODE }} \
              -e TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} \
              -e TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }} \
              registry.digitalocean.com/silkroad-api/silkroad-app:latest
          EOF
