name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY_NAME: "silkroad-app"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to DigitalOcean Docker Registry
        run: echo "${{ secrets.ACCESS_TOKEN }}" | docker login registry.digitalocean.com -u "docean" --password-stdin

      - name: Build Docker image
        run: docker build -t registry.digitalocean.com/$(echo $REGISTRY_NAME)/silkroad-app:latest .

      - name: Push Docker image to DigitalOcean Registry
        run: docker push registry.digitalocean.com/$(echo $REGISTRY_NAME)/silkroad-app:latest

    outputs:
      image_name: registry.digitalocean.com/$(echo $REGISTRY_NAME)/silkroad-app
      image_tag: latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSHKEY }}

      - name: Deploy to DigitalOcean
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_IP }} << 'EOF'
            docker stop silkroad-app || true
            docker rm silkroad-app || true
            docker pull registry.digitalocean.com/$(echo $REGISTRY_NAME)/silkroad-app:latest
            docker run -d --name silkroad-app -p 80:80 registry.digitalocean.com/$REGISTRY_NAME/silkroad-app:latest
          EOF